### ISSUE TITLE
ARM64 for Mac

### ISSUE THREAD

**Issue by revjkramer** [zturtleman/lilium-voyager#11]
I can't seem to compile an ARM64 version for M1 Mac. Any help would be appreciated.

**Comment by zturtleman** [comment]
Mac ARM64 is currently not supported. The x86_64 version should work though.

Mac ARM64 is supported by upstream ioquake3 but there is some issues with the builds of the SDL library for other platforms/archs making it overall unreleasable so I'm holding back updating. https://github.com/zturtleman/lilium-voyager/pull/9#issuecomment-1019670462

**Comment by zturtleman** [comment]
It can now be built for macOS Apple SIlicon using `./make-macosx.sh arm64` or (for arm64/x86_64 bundle) `./make-macosx-ub2.sh`. I haven't tested it, if it doesn't work you can reopen the issue.

ioEF pak92.pk3 is currently needed for correct physics, see issue #13.
