### ISSUE TITLE
ERROR: Client/Server game mismatch: baseef-1/Federation v1.16-1

### ISSUE THREAD

**Issue by rcampbel3** [zturtleman/lilium-voyager#2]
Hi,

Just recently started using lilium-voyager, and in the process of optimizing, tuning, tweaking things, I now get this error:

Do you have any idea how to resolve this?

<pre>
[...]
----- finished R_Init -----
Loading vm file vm/ui.qvm...
File "vm/ui.qvm" found in "/home/rcampbel/.local/share/lilium-voyager/baseEF/pakext2b.pk3"
VM file ui compiled to 1536209 bytes of code
ui loaded in 2023104 bytes on the hunk
42 arenas parsed
149 bots parsed
Loading vm file vm/cgame.qvm...
File "vm/cgame.qvm" found in "/home/rcampbel/.local/share/lilium-voyager/baseEF/pakext2b.pk3"
VM file cgame compiled to 1736938 bytes of code
cgame loaded in 3198336 bytes on the hunk
********************
ERROR: Client/Server game mismatch: baseef-1/Federation v1.16-1
********************
----- Server Shutdown (Server crashed: Client/Server game mismatch: baseef-1/Federation v1.16-1) -----
==== ShutdownGame ====
AAS shutdown.
</pre>

**Comment by zturtleman** [comment]
The server game logic is running a mod not compatible with pakext2b.pk3. One of the pk3 needs to be removed. Look higher in the log for which pk3 contains `vm/qagame.qvm` and try moving the pk3 somewhere else, such as a separate mod directory in /home/rcampbel/.local/share/lilium-voyager/.

**Comment by rcampbel3** [comment]
Thanks!  That did the trick.
