### ISSUE TITLE
Next Release

### ISSUE THREAD

**Issue by angrynerd** [zturtleman/lilium-voyager#3]
Hello, i really like what your doing here i was using ioEF for a while because out of the several other clients out there it was the best. Now I see this one takes advantage of all the greatest things from the newest ioquake3 updates. However seeing as Thilo's site is dead, and there hasnt been a propper release to this client in some time i was currious when the next one would be?

**Comment by zturtleman** [comment]
There will probably be a new release in next month or two. Changes since last release: A few minor bug fixes, update to SDL 2.0.8 (which breaks mouse wheel on macOS...), and major bug fixes for IQM skeletal models but IQM is not used by Elite Force.

**Comment by angrynerd** [comment]
Cool I am excitedly waiting for it to release. Also thank you for replying.

**Comment by zturtleman** [comment]
New release is out: https://clover.moe/2019/11/02/lilium-voyager-1-40-released/

Also correction to my previous comment: Lilium Voyager 1.39 had already updated to SDL 2.0.8. No change to SDL version in Lilium Voyager 1.40.
